### PR TITLE
docker:bump to 24.0.5

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
cmd/pprof/internal/fetch
expvar
net/http/cgi
cmd/pprof
net/http/cookiejar
net/http/fcgi
net/http/httptest
net/http/httputil
net/http/pprof
net/rpc
net/rpc/jsonrpc
echo


rm -f "$GOTOOLDIR"/go_bootstrap

if [ "$1" != "--no-banner" ]; then
	"$GOTOOLDIR"/dist banner
fi

---
Installed Go for linux/amd64 in /usr/src/go
Installed commands in /usr/src/go/bin

The binaries expect /usr/src/go to be copied or moved to /usr/lib/go1.4
Creating /var/log/lunar/compile/go-bootstrap-1.4.3.bz2 
Creating /var/log/lunar/install/go-bootstrap-1.4.3
Creating /var/log/lunar/md5sum/go-bootstrap-1.4.3
sed: can't read src/os/os_test.go: No such file or directory

Creating /var/log/lunar/compile/go-bootstrap2-1.19.5.bz2 
! Problem detected during PRE_BUILD

Creating /var/log/lunar/compile/go-1.20.5.bz2 
! Problem detected during PRE_BUILD

**Comment by esselfe** [comment]
Can't test because containerd fails here.

**Comment by esselfe** [comment]
So containerd works now, but docker fails with:

[...]
Building docker version 24.0.5
\+ validating "/usr/src/docker-24.0.5"
\+ creating building dir "/usr/src/docker-24.0.5"
\+ Unpacking "/var/spool/lunar/cli-24.0.5.tar.gz" in "/usr/src/docker-24.0.5"
\+ Unpacking "/var/spool/lunar/moby-24.0.5.tar.gz" in "/usr/src/docker-24.0.5"
\+ Unpacking "/var/spool/lunar/libnetwork-67e0588f1ddfaf2faf4c8cae8b7ea2876434d91c.tar.gz" in "/usr/src/docker-24.0.5"
\+ Unpacking "/var/spool/lunar/tini-0b44d3665869e46ccbac7414241b8256d6234dc4.tar.gz" in "/usr/src/docker-24.0.5"
\+ Unpacking "/var/spool/lunar/buildx-86ae8ea854e639a3267399fdf3f99e9b900f6e09.tar.gz" in "/usr/src/docker-24.0.5"
\+ Unpacking "/var/spool/lunar/app-a48f773ab0025bff4587c38d1794a9da8214e797.tar.gz" in "/usr/src/docker-24.0.5"
/var/lib/lunar/moonbase-git/zlocal/docker/PRE_BUILD: line 35: moby-24.0.5/hack/dockerfile/install/proxy.installer: No such file or directory
Invalid commit for LIBNETWORK_COMMIT, is 67e0588f1ddfaf2faf4c8cae8b7ea2876434d91c and should be

**Comment by esselfe** [comment]
Closing with https://github.com/lunar-linux/moonbase-other/pull/3047

**Pull request closed without merging**
