### PR TITLE
php: version bumped to 8.3.3

### PR DESCRIPTION
**Pull request by esselfe**

### CODE REVIEW

**Comment by esselfe** [comment]
The CI failed at the musl sha256 sum check.

**Comment by stumbles** [comment]
Retest this please.

**Comment by esselfe** [comment]
Now after the musl commit the CI fails at cargo-c with:

The package requires the Cargo feature called `strip`, but that feature is not stabilized in this version of Cargo (1.58.0 (f01b232bc 2022-01-19)).

**Comment by stumbles** [comment]
Retest this please.

**Pull request merged**
