### PR TITLE
python2-chardet:bump to 5.0.0

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
Retest this please.

**Comment by esselfe** [comment]
Fails with a python stacktrace and this "relevant" message:
AttributeError: 'module' object has no attribute '__version__'

Personally I'm starting to think python2 modules are being EOL'd...

**Comment by stumbles** [comment]
@esselfe 
python 2 is EOL as of January 2020.

**Comment by esselfe** [comment]
Closing EOL python2 module PR.

**Pull request closed without merging**
