### PR TITLE
synergy:bump to 1.14.6.19

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
/tmp/synergy-1.14.6     [  <=>               ]   4.44M  11.6MB/s    in 0.4s    

2023-08-14 16:50:18 (11.6 MB/s) - '/tmp/synergy-1.14.6.19.tar.gz' saved [4658286]

Building synergy version 1.14.6.19
CMake Error: The source directory "/usr/src/synergy-core-1.14.6.19" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Creating /var/log/lunar/compile/synergy-1.14.6.19.bz2 
! Problem detected during BUILD

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Of course. Fails on pulseaudio; importlib.metadata.PackageNotFoundError: No package metadata was found for meson

**Comment by stumbles** [comment]
Restest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Add this to line one of the BUILD;

source /etc/profile.d/qt5.rc &&

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
