### PR TITLE
gmic-qt - 2nd try

### PR DESCRIPTION
**Pull request by tbeckerson**
As mentioned with the combined gmic - gmic-qt PR from several days ago, this was separated to isolate the build fail with gmic-qt.
- I'm expecting this to fail like the previous times.
- It appears to be a Jenkins failure when building QT5, and not directly this module.

### CODE REVIEW

**Comment by tbeckerson** [comment]
retest this please

**Comment by stumbles** [comment]
I just switched out the nettle source urls for gnome. Give it a few minutes and try again.

**Comment by tbeckerson** [comment]
retest this please

**Comment by tbeckerson** [comment]
retest this please

**Pull request merged**
