### PR TITLE
i3status: bump to 2.11

### PR DESCRIPTION
**Pull request by rtlanceroad**

### CODE REVIEW

**Comment by rtlanceroad** [comment]
Retest please

**Comment by rtlanceroad** [comment]
Please retest

**Comment by Ratler** [comment]
Fixed as of commit https://github.com/lunar-linux/moonbase-other/commit/4e36141172b41b69aa8b973b64a431a178ea2462

**Comment by rtlanceroad** [comment]
Thanks for the fix.

**Pull request closed without merging**
