### PR TITLE
mongodb:bump to 6.0.1

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by esselfe** [comment]
I couldn't test, from the python2-yaml dep there was cython2 to install and it's broken, so skipping.

**Comment by lhw828** [comment]
Building mongodb version 6.0.8
scons: Reading SConscript files ...
scons: running with args /usr/bin/python3 /usr/bin/scons -j5 core tools --ssl --use-system-boost --use-system-pcre --use-system-yaml --use-system-zlib --use-system-snappy --disable-warnings-as-errors
Mkdir("build/scons")
scons version: 4.5.1
python version: 3 9 2 'final' 0
ModuleNotFoundError: No module named 'bson':
  File "/usr/src/mongodb-src-r6.0.8/SConstruct", line 1278:
    env = Environment(variables=env_vars, **envDict)
  File "/usr/lib/python3.9/site-packages/SCons/Environment.py", line 1231:
    apply_tools(self, tools, toolpath)
  File "/usr/lib/python3.9/site-packages/SCons/Environment.py", line 117:
    _ = env.Tool(tool)
  File "/usr/lib/python3.9/site-packages/SCons/Environment.py", line 2016:
    tool(self)
  File "/usr/lib/python3.9/site-packages/SCons/Tool/__init__.py", line 265:
    self.generate(env, *args, **kw)
  File "/usr/src/mongodb-src-r6.0.8/site_scons/site_tools/idl_tool.py", line 117:
    import buildscripts.idl.idl.compiler as idlc_mod
  File "/usr/src/mongodb-src-r6.0.8/buildscripts/idl/idl/compiler.py", line 40:
    from . import binder
  File "/usr/src/mongodb-src-r6.0.8/buildscripts/idl/idl/binder.py", line 39:
    from . import enum_types
  File "/usr/src/mongodb-src-r6.0.8/buildscripts/idl/idl/enum_types.py", line 38:
    import bson
Creating /var/log/lunar/compile/mongodb-6.0.8.bz2

**Comment by esselfe** [comment]
After adding python-bson and scons in DEPENDS I get:

scons: done reading SConscript files.
scons: Building targets ...
scons: *** Do not know how to make File target \`core' (/usr/src/mongodb-src-r6.0.8/core).  Stop.
scons: building terminated because of errors.
core failed: Do not know how to make File target \`core' (/usr/src/mongodb-src-r6.0.8/core).

**Comment by esselfe** [comment]
Closing with https://github.com/lunar-linux/moonbase-other/pull/2818

**Pull request closed without merging**
