### PR TITLE
python-pyqt6-webengine:bump to 6.6.0

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
Retest this please.

**Comment by lhw828** [comment]
compiling minizip Downloading source file zlib-1.3.1.tar.gz for module minizip
--2024-02-20 07:52:47--  http://www.zlib.net/current/zlib-1.3.1.tar.gz
Resolving www.zlib.net (www.zlib.net)... 85.187.148.2
Connecting to www.zlib.net (www.zlib.net)|85.187.148.2|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-02-20 07:52:48 ERROR 404: Not Found.

--2024-02-20 07:52:48--  http://download.lunar-linux.org/lunar/cache/zlib-1.3.1.tar.gz
Resolving download.lunar-linux.org (download.lunar-linux.org)... 188.226.242.178, 2a03:b0c0:0:1010::5d:b001
Connecting to download.lunar-linux.org (download.lunar-linux.org)|188.226.242.178|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-02-20 07:52:48 ERROR 404: Not Found.

I don't know how to download "minizip".
Install the package that provides the method and plugin to download it.
Building minizip version 1.3.1
Missing zlib-1.3.1.tar.gz
Lunar Install aborting.

Creating /var/log/lunar/compile/minizip-1.3.1.bz2 
! Problem detected during PRE_BUILD
Build step 'Execute managed script' marked build as failure
Discard old builds...
#4307 is removed because old than numToKeep

**Comment by lhw828** [comment]
compiling minizip Downloading source file zlib-1.3.1.tar.gz for module minizip
--2024-02-20 07:52:47--  http://www.zlib.net/current/zlib-1.3.1.tar.gz
Resolving www.zlib.net (www.zlib.net)... 85.187.148.2
Connecting to www.zlib.net (www.zlib.net)|85.187.148.2|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-02-20 07:52:48 ERROR 404: Not Found.

--2024-02-20 07:52:48--  http://download.lunar-linux.org/lunar/cache/zlib-1.3.1.tar.gz
Resolving download.lunar-linux.org (download.lunar-linux.org)... 188.226.242.178, 2a03:b0c0:0:1010::5d:b001
Connecting to download.lunar-linux.org (download.lunar-linux.org)|188.226.242.178|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-02-20 07:52:48 ERROR 404: Not Found.

I don't know how to download "minizip".
Install the package that provides the method and plugin to download it.
Building minizip version 1.3.1
Missing zlib-1.3.1.tar.gz
Lunar Install aborting.

Creating /var/log/lunar/compile/minizip-1.3.1.bz2 
! Problem detected during PRE_BUILD
Build step 'Execute managed script' marked build as failure
Discard old builds...
#4307 is removed because old than numToKeep

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by lhw828** [comment]
2024-02-20 20:30:49 (8.64 MB/s) - '/tmp/PyQt6_WebEngine-6.6.0.tar.gz' saved [31817/31817]

Building python-pyqt6-webengine version 6.6.0
pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
Querying qmake about your Qt installation...
These bindings will be built: QtWebEngineCore, QtWebEngineQuick, QtWebEngineWidgets.
Generating the QtWebEngineCore bindings...
/usr/lib/python3.11/site-packages/PyQt6/bindings/QtCore/QtCoremod.sip: line 64: '%Plugin' is deprecated and will be removed in SIP v7.0.0
Generating the QtWebEngineQuick bindings...
/usr/lib/python3.11/site-packages/PyQt6/bindings/QtCore/QtCoremod.sip: line 64: '%Plugin' is deprecated and will be removed in SIP v7.0.0
Generating the QtWebEngineWidgets bindings...
/usr/lib/python3.11/site-packages/PyQt6/bindings/QtCore/QtCoremod.sip: line 64: '%Plugin' is deprecated and will be removed in SIP v7.0.0
Generating the .pro file for the QtWebEngineCore module...
Generating the .pro file for the QtWebEngineQuick module...
Generating the .pro file for the QtWebEngineWidgets module...
Generating the top-level .pro file...
Generating the Makefiles...
sip-build: '/usr/lib/qt6/bin/qmake6 -recursive PyQt6-WebEngine.pro' failed returning 3
Creating /var/log/lunar/compile/python-pyqt6-webengine-6.6.0.bz2 
! Problem detected during BUILD

**Comment by stumbles** [comment]
@lhw828; Please remove your DETAILS update about zlib from this PR. Minizip derives its source tarball from zlib and I have updated the minizip DETAILS to reflect your core PR about zlib.

**Pull request closed without merging**
