### PR TITLE
upower: fix typo

### PR DESCRIPTION
**Pull request by esselfe**

### CODE REVIEW

**Comment by stumbles** [comment]
Failed on libgudev (typo in DEPENDS), now fixed.

Retest this please.

**Comment by stumbles** [comment]
Retest this please

**Comment by stumbles** [comment]
Pfft. Jenkins didn't lin -rc libgudev.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
