### PR TITLE
chromium: version bumped to 50.0.2661.102

### PR DESCRIPTION
**Pull request by Ratler**
- system ffmpeg is no longer a working option, revert to using bundled version.
- removed optimization fixes, doesn't seem to be necessary anymore
- revert to bundled icu4c version
- other cleanups

### CODE REVIEW

**Comment by Ratler** [comment]
please retest this

**Comment by Ratler** [comment]
retest this please

**Comment by Ratler** [comment]
retest this please

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
