### PR TITLE
birdtray - version bump

### PR DESCRIPTION
**Pull request by tbeckerson**
systray notifier for thunderbird - version bump to 1.9.0

### CODE REVIEW

**Comment by florin65** [comment]
Retest this please

**Comment by florin65** [comment]
Retest this please

**Comment by tbeckerson** [comment]
retest this please

**Comment by tbeckerson** [comment]
This broke during the compile of qt5, and never attempted the actual compile of Birdtray. The last part of the console output (when things go wrong):

`
stdout: broken pipe
FATAL: Caught exception while loading script 'Build Lunar Modules (docker)'
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
	at hudson.Proc$LocalProc.join(Proc.java:324)
	at hudson.Launcher$ProcStarter.join(Launcher.java:480)
	at org.jenkinsci.plugins.managedscripts.ScriptBuildStep.perform(ScriptBuildStep.java:171)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1818)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute managed script' marked build as failure
Discard old builds...
#1429 is removed because old than numToKeep
Setting status of b12d1efabcde21a222069067771dfb4866e0ca6a to FAILURE with url https://serenity.stderr.eu/ci-lunar/job/moonbase-other/1482/ and message: 'Build finished. '
Finished: FAILURE
`

This happened in my other PR for gmic-qt, with the same error. It appears to be a Jenkins problem?

**Pull request closed without merging**
