### PR TITLE
rp-pppoe:bump to 4.0

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
2023-08-11 03:30:48 (1.09 MB/s) - '/tmp/rp-pppoe-4.0.tar.gz' saved [139539/139539]

Building rp-pppoe version 4.0
sed: can't read scripts/pppoe-setup.in: No such file or directory

Creating /var/log/lunar/compile/rp-pppoe-4.0.bz2 
! Problem detected during PRE_BUILD

**Comment by stumbles** [comment]
Delete the PRE_BUILD.

**Comment by stumbles** [comment]
Fix the BUILD. Delete the sedit, make, cd ../gui (no such dir), cd ../src and make install.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
