### PR TITLE
wlroots: Bump to 0.17.1.

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by stumbles** [comment]
egl-wayland tanks

**Comment by esselfe** [comment]
This version of wlroots breaks sway 1.8.1 with:

meson.build:53:10: ERROR: Dependency lookup for wlroots with method 'pkgconfig' failed: Invalid version, need 'wlroots' ['<0.17.0'] found '0.17.1'.

**Comment by stumbles** [comment]
Restest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
