### PR TITLE
connman:bump to 1.42

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
CC       gsupplicant/tools_dnsproxy_standalone-supplicant.o
  CC       gsupplicant/tools_dnsproxy_standalone-dbus.o
  CC       vpn/plugins/connman_vpnd-vpn.o
  CC       vpn/connman_vpnd-main.o
  CCLD     plugins/hh2serial-gps.la
  CCLD     plugins/tist.la
  CC       scripts/libppp-plugin.lo
  CCLD     vpn/plugins/wireguard.la
  CCLD     vpn/plugins/pptp.la
scripts/libppp-plugin.c:37:10: fatal error: libppp-compat.h: No such file or directory
   37 | #include "libppp-compat.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:3594: scripts/libppp-plugin.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:2113: all] Error 2
Creating /var/log/lunar/compile/connman-1.42.bz2 
! Problem detected during BUILD

Looks like need libppp

**Comment by esselfe** [comment]
Can't test because ppp fails.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Closing with 9a188ede68..9f7aa92ba9

**Pull request closed without merging**
