### PR TITLE
udisks2: version bump to 2.1.8

### PR DESCRIPTION
**Pull request by rtlanceroad**

### CODE REVIEW

**Comment by rtlanceroad** [comment]
Retest

**Comment by rtlanceroad** [comment]
Please retest

**Comment by rtlanceroad** [comment]
The CI error is not related to udisks2.

**Comment by v4hn** [comment]
hey there,

yes, the error is related to our latest update to gcc 6.2.
Looks like the old version of spidermonkey that polkit relies on is not compatible with c++11.
I fixed it in 7d8317cba8ac27a54e645b5450293bdb606b2bab.

**Comment by v4hn** [comment]
retest this please

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by v4hn** [comment]
thanks @rtlanceroad !

**Pull request merged**
