### PR TITLE
resolvconf: Update

### PR DESCRIPTION
**Pull request by Duskmourn**

### CODE REVIEW

**Comment by Florin65** [comment]
The %MODULE is a typo. It have to be $MODULE.

**Comment by Florin65** [comment]
Will have to find a fix for:
   mv: cannot move '/etc/resolv.conf' to '/etc/resolvconf/resolv.conf.d/original': Device or resource busy

**Comment by Florin65** [comment]
The module is not needed anymore in the moonbase.

**Comment by v4hn** [comment]
> The module is not needed anymore in the moonbase.

That's a bit harsh to say, but systemd-resolved provides a functionally superior alternative.

**Pull request closed without merging**
