### PR TITLE
latex2html:bump to 2022

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by lhw828** [comment]
Retest this please.

**Comment by stumbles** [comment]
Here on my machine texlive compiles just fine with harfbuzz/hb-graphite.

Until Ratler rebuilds serenity texlive will continue failing on harfbuzz.

**Pull request merged**
