### PR TITLE
alsa-utils: version bumped to 1.2.12

### PR DESCRIPTION
**Pull request by esselfe**

### CODE REVIEW

**Comment by esselfe** [comment]
The CI failed with:

Traceback (most recent call last):
  File "/usr/bin/rst2man", line 5, in <module>
    from docutils.core import rst2man
ModuleNotFoundError: No module named 'docutils'

despite having added the docutils depends...

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
It's not compiling docutils

**Comment by stumbles** [comment]
Superseded by PR #3861. Closing.

**Pull request closed without merging**
