### PR TITLE
Spidermonkey: Version bump to 24.2.0.

### PR DESCRIPTION
**Pull request by dagbrown**
Yes, this is a bump that's been more than four years coming.

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by dagbrown** [comment]
retest

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by v4hn** [comment]
We already have this version in the `mozjs` package.

polkit fails with the current version, so florin created a new package for this version 2 years ago.
The naming is a bit unfortunate though...

**Pull request closed without merging**
