### PR TITLE
mariadb:version bumped to 10.3.11

### PR DESCRIPTION
**Pull request by lhw828**
mariadb:version bumped to 10.3.11

### CODE REVIEW

**Comment by Florin65** [comment]
The missing file was added to the moonbase.
Redo the PR please.

**Comment by lhw828** [comment]
> The missing file was added to the moonbase.
> Redo the PR please.

Do we need to adjust the BUILD file?

**Comment by Florin65** [comment]
and add the missing file (which is in the module script directory now).

**Comment by Florin65** [comment]
version 10.3.12 was released.

**Pull request closed without merging**
