### PR TITLE
dune:bump to 3.0.3

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
Is it necessary to add opam in moonbase?
https://github.com/ocaml/opam

**Comment by esselfe** [comment]
Needs a new module, opam.

**Comment by esselfe** [comment]
Also 3.6.1 is out.

**Comment by stumbles** [comment]
Closing with commit 9c3757625ebbf18012ca9f2332ce65097b261a01.

**Pull request closed without merging**
