### PR TITLE
llvm: version bump

### PR DESCRIPTION
**Pull request by v4hn**
seems to be compatible with Mesa. Please give it a spin and merge if it works.

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by Florin65** [comment]
I'll compare it with my functional one. Thank you.

**Comment by v4hn** [comment]
Also, this bump is required to build our webkit2gtk3 module.
I forgot to mention this earlier.

**Comment by Florin65** [comment]
I use cmake for my module. all work as you proposed but i can't figure out how to incorporate the R600 option yet.

**Pull request closed without merging**
