### PR TITLE
seamonkey:bump to 2.53.17

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
0:00.65   --enable-irc
 0:00.65   --enable-strip
 0:00.65   --enable-install-strip
 0:00.65   --enable-system-ffi
 0:00.65   --enable-system-pixman
 0:00.65   --enable-official-branding
 0:00.65   --enable-pulseaudio
 0:00.65   --disable-debug-symbols
 0:00.65   --disable-updater
 0:00.65   --disable-tests
 0:00.65   --disable-crashreporter
 0:00.65 checking for vcs source checkout... no
 0:00.69 checking for a shell... /bin/sh
 0:00.70 checking for host system type... x86_64-pc-linux-gnu
 0:00.71 checking for target system type... x86_64-pc-linux-gnu
 0:00.86 Determining COMM source information from sourcestamp.txt...
 0:00.86 Determining GECKO source information from sourcestamp.txt...
 0:00.99 checking whether cross compiling... no
 0:00.99 checking for the target C compiler... /var/lib/lunar/compilers/gcc
 0:01.01 checking whether the target C compiler can be used... yes
 0:01.02 Traceback (most recent call last):
 0:01.02   File "/usr/src/seamonkey-2.53.17/configure.py", line 175, in <module>
 0:01.02     sys.exit(main(sys.argv))
 0:01.02   File "/usr/src/seamonkey-2.53.17/configure.py", line 46, in main
 0:01.02     sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
 0:01.02   File "/usr/src/seamonkey-2.53.17/python/mozbuild/mozbuild/configure/__init__.py", line 492, in run
 0:01.02     raise InvalidOptionError(msg)
 0:01.02 mozbuild.configure.options.InvalidOptionError: Unknown option: --enable-system-hunspell
 0:01.09 *** Fix above errors and then restart with\
 0:01.09                "./mach build"
 0:01.09 make: *** [client.mk:114: configure] Error 1
Creating /var/log/lunar/compile/seamonkey-2.53.17.bz2 
! Problem detected during BUILD

**Comment by esselfe** [comment]
Same error here.

**Comment by stumbles** [comment]
Remove --enable-system-hunspell switch from mozconfig.

**Comment by stumbles** [comment]
Closing with commit f4bd7fb4d6ab0d70d71148aa021a1a3df95f7992

**Pull request closed without merging**
