### PR TITLE
texlive: bump to 20170524. Need to enable the xpdf headers from poppler.

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by stumbles** [comment]
retest

**Comment by stumbles** [comment]
retest please

**Comment by stumbles** [comment]
retest this please

**Comment by stumbles** [comment]
retest this please

**Comment by stumbles** [comment]
retest this please

**Comment by Ratler** [comment]
retest this please

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
