### PR TITLE
atom:bump to 1.60.0

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by stumbles** [comment]
Needs a DEPENDS with python-setuptools.

**Comment by esselfe** [comment]
Failed with:

[...]
\+ Unpacking "/var/spool/lunar/atom-1.60.0.tar.gz" in "/usr/src"
\+ Editing "src/command-installer.coffee"
sed: can't read src/command-installer.coffee: No such file or directory
\+ Editing "build/Gruntfile.coffee"
sed: can't read build/Gruntfile.coffee: No such file or directory

**Comment by stumbles** [comment]
Read; https://github.blog/2022-06-08-sunsetting-atom/#platform-linux.

I don't see a need keeping this around and needs shuffled off to /dev/null.

**Comment by esselfe** [comment]
Closing with 581cddc88b7358a5e693d7eb1f43dbe1a14fec48 , moved to crater.

**Pull request closed without merging**
