### PR TITLE
lablgtk: Bump to 3.1.4.

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
CI died.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by esselfe** [comment]
Can't test because the dependency ocaml-cairo won't build, fails with:

fatal error: ft2build.h: No such file or directory

Note that the header exists in /usr/include/freetype2/

**Comment by esselfe** [comment]
Retest this please.

**Comment by stumbles** [comment]
Closing. Replacing with lablgtk-3.1.5.

**Pull request closed without merging**
