### PR TITLE
pulseaudio: optional udev defaults to n

### PR DESCRIPTION
**Pull request by bsfc1685**
I want to see if a pulseaudio's configure doesn't fail with this
(later comment edits: catched while doing an update after rtlaneroad's first commit on i3status PR) ... we talked on IRC about it and to let florin have a thought on that
it was closed because I saw "pending" on his PR and thus wanted to let rtlanceroad have another i3status build, but I saw jenkins can trigger more than one at once :P

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by bsfc1685** [comment]
final check

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by bsfc1685** [comment]
weird... when udev defaults to yes, it's not actually built/installed on the jenkins host... at least not configure-detected

**Pull request merged**
