### PR TITLE
enblend-enfuse:add a depends

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by stumbles** [comment]
Retest this please.

**Comment by lhw828** [comment]
Retest this please.

**Comment by lhw828** [comment]
Note:When the PR https://github.com/lunar-linux/moonbase-other/pull/1814 is merged, try the retest this again.

**Comment by lhw828** [comment]
Retest this please.

**Comment by stumbles** [comment]
Closing with commit 2df74ca1e8d3b0ae16deb85e3f0ccf6f1c5460ea

**Pull request closed without merging**
