### PR TITLE
php: version bumped to 8.3.11

### PR DESCRIPTION
**Pull request by esselfe**
Also change tabs for spaces.

### CODE REVIEW

**Comment by esselfe** [comment]
The CI failed at xmlto with:

```
gcc -DHAVE_CONFIG_H -I.     -O2 -march=x86-64 -fno-plt -fexceptions -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-clash-protection -MT xmlif/xmlif.o -MD -MP -MF $depbase.Tpo -c -o xmlif/xmlif.o xmlif/xmlif.c &&\
mv -f $depbase.Tpo $depbase.Po
xmlif/xmlif.l:46:8: error: type defaults to 'int' in declaration of 'ifsense' [-Wimplicit-int]
   46 | static ifsense;                 /* sense of last `if' or unless seen */
      |        ^~~~~~~
xmlif/xmlif.l:243:1: error: return type defaults to 'int' [-Wimplicit-int]
  243 | {
      | ^   
make[1]: *** [Makefile:772: xmlif/xmlif.o] Error 1
make[1]: Leaving directory '/usr/src/xmlto-0.0.28'
```

**Comment by esselfe** [comment]
Ok I found a patch for xmlto. https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=f2c2beb6007ad270dff9aacedbcf2ef0946eaa74

**Comment by esselfe** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
