### PR TITLE
thailatex:bump to 0.5.1

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by lhw828** [comment]
Retest this please.

**Comment by lhw828** [comment]
Retest this please.

**Comment by lhw828** [comment]
Retest this please.

**Comment by dagbrown** [comment]
Retest this please.

**Comment by esselfe** [comment]
Passed on my laptop.

**Pull request merged**
