### PR TITLE
owncloudclient: Bump to 5.2.0.12726.

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by stumbles** [comment]
Fails on python-markupsafe (core) not finding python-setuptools (core).  A CI issue.

**Comment by esselfe** [comment]
Can't test because qtwebkit fails with:

`error: 'uint32_t' does not name a type`

**Comment by stumbles** [comment]
qtwebkit has bee?n reworked. Give it another go

**Comment by stumbles** [comment]
Closing. Needs complete rework.

**Pull request closed without merging**
