### PR TITLE
foomatic-db-nonfree:bump to current

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by esselfe** [comment]
Can't test, dep foomatic-db won't download.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
*** You need libgpg-error to build this program.
**  This library is for example available at
***   https://gnupg.org/ftp/gcrypt/gpgrt
*** (at least version 1.46 is required.)
***
configure: error: 
***
*** Required libraries not found. Please consult the above messages
*** and install them before running configure again.
***
Creating /var/log/lunar/compile/gnupg-2.4.3.bz2 
! Problem detected during BUILD

**Comment by stumbles** [comment]
Closing with #3190, version bump.

**Pull request closed without merging**
