### PR TITLE
chromium:bump to 120.0.6073.0

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
make[3]: Entering directory '/usr/src/libgnome-keyring-3.12.0/library'
  CC       gkr-callback.lo
  CC       gkr-debug.lo
  CC       gkr-misc.lo
  CC       gkr-operation.lo
  CC       gkr-session.lo
  CC       gnome-keyring.lo
gkr-debug.c: In function 'on_gkr_log_debug':
gkr-debug.c:88:2: warning: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
   88 |  write (1, gstring->str, gstring->len);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC       gnome-keyring-memory.lo
  CC       gnome-keyring-utils.lo
  CCLD     libgnome-keyring.la
  CCLD     libgnome-keyring-testable.la
  GISCAN   GnomeKeyring-1.0.gir
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 98, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/lib/gobject-introspection/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 34, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ModuleNotFoundError: No module named 'giscanner._giscanner'
make[3]: *** [/usr/share/gobject-introspection-1.0/Makefile.introspection:156: GnomeKeyring-1.0.gir] Error 1
make[3]: Leaving directory '/usr/src/libgnome-keyring-3.12.0/library'
make[2]: *** [Makefile:769: all-recursive] Error 1
make[2]: Leaving directory '/usr/src/libgnome-keyring-3.12.0/library'
make[1]: *** [Makefile:481: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/libgnome-keyring-3.12.0'
make: *** [Makefile:412: all] Error 2
Creating /var/log/lunar/compile/libgnome-keyring-3.12.0.bz2 
! Problem detected during BUILD

**Comment by esselfe** [comment]
Can't test, insufficient hardware specs here.

**Comment by lhw828** [comment]
/usr/include/absl/strings/internal/str_format/bind.h: In instantiation of 'absl::lts_20230802::str_format_internal::FormatSpecTemplate<Args>::FormatSpecTemplate(const char*) [with absl::lts_20230802::FormatConversionCharSet ...Args = {(absl::lts_20230802::FormatConversionCharSet)524292, (absl::lts_20230802::FormatConversionCharSet)655355, (absl::lts_20230802::FormatConversionCharSet)655355, (absl::lts_20230802::FormatConversionCharSet)524292, (absl::lts_20230802::FormatConversionCharSet)655355}]':
re2/dfa.cc:1007:70:   required from here
/usr/include/absl/strings/internal/str_format/bind.h:164:45: error: no matching function for call to 'absl::lts_20230802::UntypedFormatSpec::UntypedFormatSpec(const char*&)'
  164 |   FormatSpecTemplate(const char* s) : Base(s) {}  // NOLINT
      |                                             ^
In file included from /usr/include/absl/crc/crc32c.h:32,
                 from /usr/include/absl/crc/internal/crc_cord_state.h:23,
                 from /usr/include/absl/strings/cord.h:79,
                 from /usr/include/absl/container/internal/hash_function_defaults.h:56,
                 from /usr/include/absl/container/flat_hash_map.h:41,
                 from re2/dfa.cc:39:
/usr/include/absl/strings/str_format.h:107:12: note: candidate: 'absl::lts_20230802::UntypedFormatSpec::UntypedFormatSpec(const absl::lts_20230802::str_format_internal::ParsedFormatBase*)'
  107 |   explicit UntypedFormatSpec(const str_format_internal::ParsedFormatBase* pc)
      |            ^~~~~~~~~~~~~~~~~
/usr/include/absl/strings/str_format.h:107:75: note:   no known conversion for argument 1 from 'const char*' to 'const absl::lts_20230802::str_format_internal::ParsedFormatBase*'
  107 |   explicit UntypedFormatSpec(const str_format_internal::ParsedFormatBase* pc)
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/absl/strings/str_format.h:79,
                 from /usr/include/absl/crc/crc32c.h:32,
                 from /usr/include/absl/crc/internal/crc_cord_state.h:23,
                 from /usr/include/absl/strings/cord.h:79,
                 from /usr/include/absl/container/internal/hash_function_defaults.h:56,
                 from /usr/include/absl/container/flat_hash_map.h:41,
                 from re2/dfa.cc:39:
/usr/include/absl/strings/internal/str_format/bind.h: In instantiation of 'absl::lts_20230802::str_format_internal::FormatSpecTemplate<Args>::FormatSpecTemplate(const char*) [with absl::lts_20230802::FormatConversionCharSet ...Args = {(absl::lts_20230802::FormatConversionCharSet)655355, (absl::lts_20230802::FormatConversionCharSet)655355, (absl::lts_20230802::FormatConversionCharSet)655355, (absl::lts_20230802::FormatConversionCharSet)524292, (absl::lts_20230802::FormatConversionCharSet)655355}]':
re2/dfa.cc:1717:69:   required from here
/usr/include/absl/strings/internal/str_format/bind.h:164:45: error: no matching function for call to 'absl::lts_20230802::UntypedFormatSpec::UntypedFormatSpec(const char*&)'
  164 |   FormatSpecTemplate(const char* s) : Base(s) {}  // NOLINT
      |                                             ^
In file included from /usr/include/absl/crc/crc32c.h:32,
                 from /usr/include/absl/crc/internal/crc_cord_state.h:23,
                 from /usr/include/absl/strings/cord.h:79,
                 from /usr/include/absl/container/internal/hash_function_defaults.h:56,
                 from /usr/include/absl/container/flat_hash_map.h:41,
                 from re2/dfa.cc:39:
/usr/include/absl/strings/str_format.h:107:12: note: candidate: 'absl::lts_20230802::UntypedFormatSpec::UntypedFormatSpec(const absl::lts_20230802::str_format_internal::ParsedFormatBase*)'
  107 |   explicit UntypedFormatSpec(const str_format_internal::ParsedFormatBase* pc)
      |            ^~~~~~~~~~~~~~~~~
/usr/include/absl/strings/str_format.h:107:75: note:   no known conversion for argument 1 from 'const char*' to 'const absl::lts_20230802::str_format_internal::ParsedFormatBase*'
  107 |   explicit UntypedFormatSpec(const str_format_internal::ParsedFormatBase* pc)
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/absl/container/internal/hash_function_defaults.h:56,
                 from /usr/include/absl/container/flat_hash_map.h:41,
                 from re2/dfa.cc:39:
/usr/include/absl/strings/cord.h: In instantiation of 'H absl::lts_20230802::Cord::HashFragmented(H) const [with H = absl::lts_20230802::hash_internal::MixingHashState]':
/usr/include/absl/strings/cord.h:783:28:   required from 'H absl::lts_20230802::AbslHashValue(H, const absl::lts_20230802::Cord&) [with H = absl::lts_20230802::hash_internal::MixingHashState]'
/usr/include/absl/hash/internal/hash.h:891:27:   required from 'static absl::lts_20230802::enable_if_t<std::is_same<H, decltype (absl::lts_20230802::hash_internal::AbslHashValue(std::move(state), value))>::value, H> absl::lts_20230802::hash_internal::HashSelect::HashValueProbe::Invoke(H, const T&) [with H = absl::lts_20230802::hash_internal::MixingHashState; T = absl::lts_20230802::Cord; absl::lts_20230802::enable_if_t<std::is_same<H, decltype (absl::lts_20230802::hash_internal::AbslHashValue(std::move(state), value))>::value, H> = absl::lts_20230802::hash_internal::MixingHashState; decltype (absl::lts_20230802::hash_internal::AbslHashValue(std::move(state), value)) = absl::lts_20230802::hash_internal::MixingHashState]'
/usr/include/absl/hash/internal/hash.h:1264:73:   required from 'static H absl::lts_20230802::hash_internal::HashStateBase<H>::combine(H, const T&, const Ts& ...) [with T = absl::lts_20230802::Cord; Ts = {}; H = absl::lts_20230802::hash_internal::MixingHashState]'
/usr/include/absl/hash/internal/hash.h:999:39:   required from 'static size_t absl::lts_20230802::hash_internal::MixingHashState::hash(const T&) [with T = absl::lts_20230802::Cord; typename std::enable_if<(! absl::lts_20230802::conjunction<std::is_integral<_Tp>, absl::lts_20230802::hash_internal::is_uniquely_represented<T, void> >::value), int>::type <anonymous> = 0; size_t = long unsigned int]'
/usr/include/absl/hash/internal/hash.h:1253:33:   required from 'size_t absl::lts_20230802::hash_internal::HashImpl<T>::operator()(const T&) const [with T = absl::lts_20230802::Cord; size_t = long unsigned int]'
/usr/include/absl/container/internal/hash_function_defaults.h:81:38:   required from here
/usr/include/absl/strings/cord.h:1020:17: error: cannot convert 'absl::lts_20230802::Cord::HashFragmented<absl::lts_20230802::hash_internal::MixingHashState>::<lambda(int)>' to 'int'
 1020 |     ForEachChunk([&combiner, &hash_state](absl::string_view chunk) {
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1021 |       hash_state = combiner.add_buffer(std::move(hash_state), chunk.data(),
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1022 |                                        chunk.size());
      |                                        ~~~~~~~~~~~~~~
 1023 |     });
      |     ~~           
/usr/include/absl/strings/cord.h:1591:48: note:   initializing argument 1 of 'void absl::lts_20230802::Cord::ForEachChunk(int) const'
 1591 |     absl::FunctionRef<void(absl::string_view)> callback) const {
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
make: *** [Makefile:204: obj/re2/dfa.o] Error 1
Creating /var/log/lunar/compile/re2-2023-09-01.bz2

**Comment by esselfe** [comment]
Ok so I got myself a dedicated server to test this... it fails with:

'chromium/config/Chrome/mac//x64/libavutil/ffversion.h' -> 'chromium/config/Chrome/ios/x64/libavutil/ffversion.h'
Copied all existing newer configs successfully.
Traceback (most recent call last):
  File "/usr/src/chromium-120.0.6073.0/third_party/ffmpeg/chromium/scripts/generate_gn.py", line 42, in <module>
    ROBO_CONFIGURATION = config.RoboConfiguration(quiet=True)
  File "/usr/src/chromium-120.0.6073.0/third_party/ffmpeg/chromium/scripts/robo_lib/config.py", line 38, in __init__
    self.EnsureHostInfo()
  File "/usr/src/chromium-120.0.6073.0/third_party/ffmpeg/chromium/scripts/robo_lib/config.py", line 161, in EnsureHostInfo
    raise Exception("Couldn't determine OS flavor (needed to install packages)")
Exception: Couldn't determine OS flavor (needed to install packages)
/usr/src/chromium-120.0.6073.0
ERROR at //build/config/rust.gni:128:24: Script returned non-zero exit code.
      rustc_revision = exec_script("//tools/rust/update_rust.py",
                       ^----------
Current dir: /usr/src/chromium-120.0.6073.0/out/Release/
Command: python3 /usr/src/chromium-120.0.6073.0/tools/rust/update_rust.py --print-package-version
Returned 1 and printed out:

The expected Rust version is 5236c8e1fa25c45f11f02ae72fc27f64d86ba606-1-llvmorg-18-init-7785-geef35c28 but the actual version is None
Did you run "gclient sync"?

See //BUILD.gn:17:1: whence it was imported.
import("//build/config/rust.gni")
^-------------------------------

**Comment by lhw828** [comment]
> Ok so I got myself a dedicated server to test this... it fails with:
> 
> 'chromium/config/Chrome/mac//x64/libavutil/ffversion.h' -> 'chromium/config/Chrome/ios/x64/libavutil/ffversion.h' Copied all existing newer configs successfully. Traceback (most recent call last): File "/usr/src/chromium-120.0.6073.0/third_party/ffmpeg/chromium/scripts/generate_gn.py", line 42, in ROBO_CONFIGURATION = config.RoboConfiguration(quiet=True) File "/usr/src/chromium-120.0.6073.0/third_party/ffmpeg/chromium/scripts/robo_lib/config.py", line 38, in **init** self.EnsureHostInfo() File "/usr/src/chromium-120.0.6073.0/third_party/ffmpeg/chromium/scripts/robo_lib/config.py", line 161, in EnsureHostInfo raise Exception("Couldn't determine OS flavor (needed to install packages)") Exception: Couldn't determine OS flavor (needed to install packages) /usr/src/chromium-120.0.6073.0 ERROR at //build/config/rust.gni:128:24: Script returned non-zero exit code. rustc_revision = exec_script("//tools/rust/update_rust.py", ^---------- Current dir: /usr/src/chromium-120.0.6073.0/out/Release/ Command: python3 /usr/src/chromium-120.0.6073.0/tools/rust/update_rust.py --print-package-version Returned 1 and printed out:
> 
> The expected Rust version is 5236c8e1fa25c45f11f02ae72fc27f64d86ba606-1-llvmorg-18-init-7785-geef35c28 but the actual version is None Did you run "gclient sync"?
> 
> See //BUILD.gn:17:1: whence it was imported. import("//build/config/rust.gni") ^-------------------------------

The following content comes from AI's response to this error

Here is the response in English:

The error indicates that the expected version of Rust and LLVM during Chromium compilation does not match the actual version installed on the system. 

Some things you can try:

1. Check if you have properly run `gclient sync` which downloads the required third party dependencies.

2. Uninstall the existing Rust and LLVM versions and reinstall the specific versions required by Chromium, which can be found in the BUILD.gn file.

3. Manually run the `update_rust.py` script in the compile directory to update the Rust version. 

4. Set environment variables to point to the local Rust and LLVM installation directories to avoid looking for them automatically during compilation.

5. Upgrade your OS or install dependency software to their latest versions to resolve any version compatibility issues.

6. Try regenerating with `gn gen` and then reconfiguring Rust upgrade. 

7. Compile in a different OS or virtual environment to check for environment variable problems.

8. Seek help from the Chromium community - others may have solved similar problems before. 

It's also important to check if it's a compile configuration issue or your local environment simply does not support the requirements. Analyze the error messages and compile logs to find the root cause. Provide more details if the above does not resolve it to get more targeted help.

**Pull request closed without merging**
