### PR TITLE
cegui:bump to 1.1.2

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by esselfe** [comment]
The URL is broken.

**Comment by esselfe** [comment]
After correcting the hash turns out it extracts to /usr/src/ceed-cpp-1.1.2

**Comment by esselfe** [comment]
Well there's no configure script, no cmake files, no meson either... someone gotta find how to build this :P

**Comment by stumbles** [comment]
That's not the right source url link for cegui.

**Comment by stumbles** [comment]
The correct url for cegui download is; https://github.com/cegui/cegui/ and their current version is the same as that in moonbase, 0.8.7.

Closing; invalid.

**Pull request closed without merging**
