### PR TITLE
eudev:bump to 3.2.12

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by esselfe** [comment]
There's a missing libxslt in DEPENDS and even there it fails to parse the remote xsl sheets.

**Comment by stumbles** [comment]
Try adding this to BUILD;

export XML_CATALOG_FILES=/etc/xml/catalog &&

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
`]0;b4e1d3de122c lin[4164]: compiling eudev WARNING: systemd conflicts with module eudev
eudev: Do you want to remove module systemd ?  [n] ERROR: Cannot continue installing conflicting modules, exiting!`

Add some logic to PRE_BUILD to lrm systemd?

**Comment by esselfe** [comment]
See https://github.com/lunar-linux/moonbase-other/pull/4199

**Pull request closed without merging**
