### PR TITLE
cairo: changed cairo's poppler dep to required

### PR DESCRIPTION
**Pull request by bsfc1685**

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by bsfc1685** [comment]
well it's "--enable-pdf=[no/auto/yes]" as per ./configure --help |grep enable-pdf ...  and I guess --disable/enable-pdf by the configure run

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by bsfc1685** [comment]
the build succeeded, but the PDF support still is not enabled... I don't get it :P libreoffice-bin will wait unless someone else has an idea, somewhen, sorry there :)

**Pull request closed without merging**
