### PR TITLE
Add to Moonbase: PlayOnLinux

### PR DESCRIPTION
**Pull request by Duskmourn**
for real this time I swear

### CODE REVIEW

**Comment by stumbles** [comment]
Retest this please.

**Comment by esselfe** [comment]
Can't test because its dependency (wxPython) won't build.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Lets redo this with a new PR. Closing

**Pull request closed without merging**
