### PR TITLE
gimp: version bumped to 2.10.38

### PR DESCRIPTION
**Pull request by esselfe**

### CODE REVIEW

**Comment by esselfe** [comment]
The CI failed at gtk+-2 with:

`sed: can't read Makefile.in: No such file or directory`

**Comment by esselfe** [comment]
This time the CI failed with:

Building python-lxml version 5.2.2
/usr/bin/python: No module named build

Looks like the python modules are broken again after the python minor bump.

**Comment by stumbles** [comment]
Retest this please.

**Comment by esselfe** [comment]
This time the CI can't find npth-1.7.tar.bz2

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
