### PR TITLE
fwupd:bump to 1.7.7

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
Retest this please.

**Comment by lhw828** [comment]
Retest this please.

**Comment by lhw828** [comment]
Building json-glib version 1.6.6
Traceback (most recent call last):
  File "/usr/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==0.60.1', 'console_scripts', 'meson')())
  File "/usr/bin/meson", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for meson
Creating /var/log/lunar/compile/json-glib-1.6.6.bz2 
! Problem detected during BUILD

**Comment by stumbles** [comment]
Closing with commit 3a5ee35c75adc750ed701bf5547661ddcb216da3 (bumps to 1.8.0)

**Pull request closed without merging**
