### PR TITLE
llvm: version bump & cmake build

### PR DESCRIPTION
**Pull request by v4hn**
This is based on florin's bump

### CODE REVIEW

**Comment by Florin65** [comment]
I think the default for R600 option have to be "n" in the CONFIGURE file. Many users do not have a Radeon video card.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by Florin65** [comment]
It installs fine. Funny thing is that the new tarball is longer with 5 bytes than the previous compiled one. So, the automatic select of targets does a pretty good job. However with the new setup it might be compiled a R600 enabled install on systems without a Radeon GPU i guess.

**Comment by v4hn** [comment]
I changed the R600 default to n.
I don't have a strong opinion on this one.

If it's otherwise fine, please merge the request.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
