### PR TITLE
ndctl:bump to v78

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by esselfe** [comment]
Failed with "meson.build:147:15: ERROR: Dependency "libtraceevent" not found, tried pkgconfig and cmake"

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Closing with https://github.com/lunar-linux/moonbase-other/commit/3feebd99b968288da8912725b8cf59393f2ac449

**Pull request closed without merging**
