### PR TITLE
darktable:bump to 4.4.2

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by stumbles** [comment]
Retest this please.

**Comment by esselfe** [comment]
Can't test because GraphicsMagick fails.

**Comment by esselfe** [comment]
Now that GraphicsMagick works, it fails with:

[...]
[271/927] Checking validity of wb_presets.json
FAILED: share/darktable/CMakeFiles/validate_wbpresets_json /usr/src/darktable-4.4.2/darktable-4.4.2/share/darktable/CMakeFiles/validate_wbpresets_json 
cd /usr/src/darktable-4.4.2/data && /usr/bin/jsonschema -i /usr/src/darktable-4.4.2/data/wb_presets.json /usr/src/darktable-4.4.2/data/wb_presets.schema
Traceback (most recent call last):
  File "/usr/bin/jsonschema", line 5, in <module>
    from jsonschema.cli import main
  File "/usr/lib/python3.10/site-packages/jsonschema/__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "/usr/lib/python3.10/site-packages/jsonschema/_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "/usr/lib/python3.10/site-packages/jsonschema/exceptions.py", line 15, in <module>
    from referencing.exceptions import Unresolvable as _Unresolvable
ModuleNotFoundError: No module named 'referencing'
[272/927] Building CXX object bin/external/LibRaw-cmake/CMakeFiles/raw_r.dir/__/LibRaw/src/metadata/sony.cpp.o
[273/927] Generating org.darktable.darktable.desktop
Merging translations into /usr/src/darktable-4.4.2/darktable-4.4.2/share/darktable/org.darktable.darktable.desktop.
[274/927] Generating ../metainfo/org.darktable.darktable.appdata.xml
Merging translations into /usr/src/darktable-4.4.2/darktable-4.4.2/bin/../share/metainfo/org.darktable.darktable.appdata.xml.
CREATED /usr/src/darktable-4.4.2/darktable-4.4.2/bin/../share/metainfo/org.darktable.darktable.appdata.xml
ninja: build stopped: subcommand failed.

**Comment by stumbles** [comment]
Closing. Replaced by PR#3348.

**Pull request closed without merging**
