### PR TITLE
chromium: version bumped to 45.0.2454.99

### PR DESCRIPTION
**Pull request by Ratler**

### CODE REVIEW

**Comment by Ratler** [comment]
retest this please

**Comment by Ratler** [comment]
3rd time is the charm, retest this please

**Comment by Ratler** [comment]
hopefully last dependency fix, retest this please

**Comment by Ratler** [comment]
retest this please

**Comment by Ratler** [comment]
retest this please

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
