### PR TITLE
python-pyqt6-webengine: Bump to 6.6.0 and adjust bUILD.

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by lhw828** [comment]
CI show this:

Building python-pyqt6-webengine version 6.6.0
pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
Querying qmake about your Qt installation...
/usr/lib/qt6/bin/qmake6 -query
These bindings will be built: QtWebEngineCore, QtWebEngineQuick, QtWebEngineWidgets.
Generating the QtWebEngineCore bindings...
/usr/lib/python3.11/site-packages/PyQt6/bindings/QtCore/QtCoremod.sip: line 64: '%Plugin' is deprecated and will be removed in SIP v7.0.0
Generating the QtWebEngineQuick bindings...
/usr/lib/python3.11/site-packages/PyQt6/bindings/QtCore/QtCoremod.sip: line 64: '%Plugin' is deprecated and will be removed in SIP v7.0.0
Generating the QtWebEngineWidgets bindings...
/usr/lib/python3.11/site-packages/PyQt6/bindings/QtCore/QtCoremod.sip: line 64: '%Plugin' is deprecated and will be removed in SIP v7.0.0
Generating the .pro file for the QtWebEngineCore module...
Generating the .pro file for the QtWebEngineQuick module...
Generating the .pro file for the QtWebEngineWidgets module...
Generating the top-level .pro file...
Generating the Makefiles...
/usr/lib/qt6/bin/qmake6 -recursive PyQt6-WebEngine.pro
sip-build: '/usr/lib/qt6/bin/qmake6 -recursive PyQt6-WebEngine.pro' failed returning 3
Info: creating stash file /usr/src/PyQt6_WebEngine-6.6.0/build/.qmake.stash
Reading /usr/src/PyQt6_WebEngine-6.6.0/build/QtWebEngineCore/QtWebEngineCore.pro
Project ERROR: Unknown module(s) in QT: webenginecore
Creating /var/log/lunar/compile/python-pyqt6-webengine-6.6.0.bz2 
! Problem detected during BUILD
Build step 'Execute managed script' marked build as failure

**Comment by stumbles** [comment]
Ah. Heres the problem;

`WARNING: QtWebEngine won't be built. node.js version 14 or later is required.
WARNING: QtPdf won't be built. node.js version 14 or later is required.`

Current moonbase node is 21.6.2 and CI node is to old. Which explains;

`Project ERROR: Unknown module(s) in QT: webenginecore`

Which is provided by; qt6-webengine.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
CI can't handle this as it takes 5+ hours to complete. Merging anyway.

**Pull request merged**
