### PR TITLE
docker: version bumped to 24.0.5

### PR DESCRIPTION
**Pull request by esselfe**

### CODE REVIEW

**Comment by esselfe** [comment]
Fixes the "Invalid Host header" error when trying to run a container. (docker 20.10.5)

**Comment by esselfe** [comment]
The CI failed because the go it has is broken.

**Comment by stumbles** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Review by stumbles — APPROVED** [review]
Good to go.

**Pull request merged**
