### PR TITLE
Vulkan-Loader:bump to 1.3.281

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
-- Build files have been written to: /usr/src/Vulkan-Loader-1.3.281/Vulkan-Loader-oosb
[  4%] Building C object loader/CMakeFiles/asm_offset.dir/asm_offset.c.o
In file included from /usr/src/Vulkan-Loader-1.3.281/loader/loader_common.h:39,
                 from /usr/src/Vulkan-Loader-1.3.281/loader/asm_offset.c:32:
/usr/src/Vulkan-Loader-1.3.281/loader/generated/vk_layer_dispatch_table.h:179:5: error: unknown type name 'PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsKHR'
  179 |     PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsKHR GetPhysicalDeviceCalibrateableTimeDomainsKHR;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/Vulkan-Loader-1.3.281/loader/generated/vk_layer_dispatch_table.h:619:5: error: unknown type name 'PFN_vkCmdSetRenderingAttachmentLocationsKHR'
  619 |     PFN_vkCmdSetRenderingAttachmentLocationsKHR CmdSetRenderingAttachmentLocationsKHR;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/Vulkan-Loader-1.3.281/loader/generated/vk_layer_dispatch_table.h:620:5: error: unknown type name 'PFN_vkCmdSetRenderingInputAttachmentIndicesKHR'
  620 |     PFN_vkCmdSetRenderingInputAttachmentIndicesKHR CmdSetRenderingInputAttachmentIndicesKHR;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/Vulkan-Loader-1.3.281/loader/generated/vk_layer_dispatch_table.h:683:5: error: unknown type name 'PFN_vkCmdSetLineStippleKHR'
  683 |     PFN_vkCmdSetLineStippleKHR CmdSetLineStippleKHR;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/Vulkan-Loader-1.3.281/loader/generated/vk_layer_dispatch_table.h:686:5: error: unknown type name 'PFN_vkGetCalibratedTimestampsKHR'
  686 |     PFN_vkGetCalibratedTimestampsKHR GetCalibratedTimestampsKHR;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/Vulkan-Loader-1.3.281/loader/generated/vk_layer_dispatch_table.h:689:5: error: unknown type name 'PFN_vkCmdBindDescriptorSets2KHR'
  689 |     PFN_vkCmdBindDescriptorSets2KHR CmdBindDescriptorSets2KHR;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/Vulkan-Loader-1.3.281/loader/generated/vk_layer_dispatch_table.h:690:5: error: unknown type name 'PFN_vkCmdPushConstants2KHR'
  690 |     PFN_vkCmdPushConstants2KHR CmdPushConstants2KHR;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/Vulkan-Loader-1.3.281/loader/generated/vk_layer_dispatch_table.h:691:5: error: unknown type name 'PFN_vkCmdPushDescriptorSet2KHR'
  691 |     PFN_vkCmdPushDescriptorSet2KHR CmdPushDescriptorSet2KHR;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/Vulkan-Loader-1.3.281/loader/generated/vk_layer_dispatch_table.h:692:5: error: unknown type name 'PFN_vkCmdPushDescriptorSetWithTemplate2KHR'
  692 |     PFN_vkCmdPushDescriptorSetWithTemplate2KHR CmdPushDescriptorSetWithTemplate2KHR;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/Vulkan-Loader-1.3.281/loader/generated/vk_layer_dispatch_table.h:693:5: error: unknown type name 'PFN_vkCmdSetDescriptorBufferOffsets2EXT'
  693 |     PFN_vkCmdSetDescriptorBufferOffsets2EXT CmdSetDescriptorBufferOffsets2EXT;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/Vulkan-Loader-1.3.281/loader/generated/vk_layer_dispatch_table.h:694:5: error: unknown type name 'PFN_vkCmdBindDescriptorBufferEmbeddedSamplers2EXT'
  694 |     PFN_vkCmdBindDescriptorBufferEmbeddedSamplers2EXT CmdBindDescriptorBufferEmbeddedSamplers2EXT;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/src/Vulkan-Loader-1.3.281/loader/loader_common.h:40:
/usr/src/Vulkan-Loader-1.3.281/loader/generated/vk_loader_extensions.h:352:5: error: unknown type name 'PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsKHR'
  352 |     PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsKHR GetPhysicalDeviceCalibrateableTimeDomainsKHR;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [loader/CMakeFiles/asm_offset.dir/build.make:76: loader/CMakeFiles/asm_offset.dir/asm_offset.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:119: loader/CMakeFiles/asm_offset.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Creating /var/log/lunar/compile/Vulkan-Loader-1.3.281.bz2

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
