### PR TITLE
qemu:bump to 7.1.0

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by stumbles** [comment]
I am puzzled how this error can exist in a PR;

ERROR: unknown option --enable-libxml2

**Comment by esselfe** [comment]
Despite correcting the 3 options the module fails during install:
`ninja: error: '/usr/bin/qemu-keymap', needed by 'pc-bios/keymaps/ar', missing and no known rule to make it`

**Comment by esselfe** [comment]
Also 7.2.0 is out.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
