### PR TITLE
llvm: version bumped to 3.7.1.

### PR DESCRIPTION
**Pull request by Florin65**
Another llvm module which use cmake for build.
I haven't figured yet how can we use the R600 option with it.

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by v4hn** [comment]
Is there any particular reason to switch to the cmake build?

doc/Packaging.rst still lists the autotools options for packaging.

**Comment by v4hn** [comment]
Ok, I just talked to someone on the #llvm channel.
cmake is the officially recommended build system these days,
and autotools support will be removed after 3.8.

So, your request is the way to go.

I'll patch it up a bit and add a new request.

**Comment by Florin65** [comment]
Great. Thank you.

**Pull request merged**
