### PR TITLE
docker-compose:bump to 2.10.0

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by esselfe** [comment]
Can't test because dependencies won't build.

**Comment by lhw828** [comment]
2023-07-20 06:44:18 (965 KB/s) - '/tmp/pyrsistent-0.19.0.tar.gz' saved [104177]

Building python-pyrsistent version 0.19.0
Traceback (most recent call last):
  File "/usr/src/pyrsistent-0.19.0/setup.py", line 2, in <module>
    from setuptools import setup, Extension
ModuleNotFoundError: No module named 'setuptools'
cp: cannot stat '/usr/src/pyrsistent-0.19.0/__pythondest3/*': No such file or directory
Creating /var/log/lunar/compile/python-pyrsistent-0.19.0.bz2

**Comment by stumbles** [comment]
Retest this please.

**Comment by esselfe** [comment]
Fails with:

python3: can't open file '/usr/src/compose-2.20.3/setup.py': [Errno 2] No such file or directory

It seems running make in the source directory works though.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Fails on rust too old for python-bcrypt.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Go module is busted;

`Creating /var/log/lunar/compile/go-bootstrap2-1.19.5.bz2 
Creating /var/log/lunar/install/go-bootstrap2-1.19.5
Creating /var/log/lunar/md5sum/go-bootstrap2-1.19.5
find: '/usr/lib/go': No such file or directory
Removed module: go-bootstrap
Building Go cmd/dist using /usr/lib/go1.19. (go1.19.5 linux/amd64)
cmd/dist
found packages main (build.go) and building_Go_requires_Go_1_20_6_or_later (notgo120.go) in /usr/src/go/src/cmd/dist
Creating /var/log/lunar/compile/go-1.22.0.bz2 
! Problem detected during BUILD`

**Comment by stumbles** [comment]
Superseded by https://github.com/lunar-linux/moonbase-other/pull/3477, closing.

**Pull request closed without merging**
