### PR TITLE
Audacity：bump to 3.4.2

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
checking for clock_gettime... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for openssl... yes
checking for ogg >= 1.3 opus >= 1.0.1... no
configure: error: Package requirements (ogg >= 1.3 opus >= 1.0.1) were not met:

Package dependency requirement 'opus >= 1.0.1' could not be satisfied.
Package 'opus' has version '0', required version is '>= 1.0.1'

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables DEPS_CFLAGS
and DEPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Creating /var/log/lunar/compile/opusfile-0.12.bz2

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Failed on retrieval of vamp-plugin-sdk. Push a commit to fix that.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Fails on missing depends wxGTK.

**Comment by stumbles** [comment]
Closing with commit f2b3b3dfd30dfc570fcaba3d46d2970eea8dce34

**Pull request closed without merging**
