### PR TITLE
gummi: fix source URL and removed autogen.sh

### PR DESCRIPTION
**Pull request by esselfe**

### CODE REVIEW

**Comment by stumbles** [comment]
Missing gtksourceview3.

**Comment by esselfe** [comment]
The CI failed with:

Copying file m4/wint_t.m4
Copying file m4/xsize.m4
Copying file po/Makevars.template
configure.ac:196: error: macro GTK_DOC_CHECK is not defined; is a m4 file missing?
/usr/share/aclocal/ax_require_defined.m4:35: AX_REQUIRE_DEFINED is expanded from...
configure.ac:196: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal: error: /usr/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1
Creating /var/log/lunar/compile/gtksourceview3-3.24.11.bz2

I'll have a look at gtksourceview3.

**Comment by esselfe** [comment]
I can't replicate this error here.

**Comment by stumbles** [comment]
In the BUILD try autoreconf -fi.

**Comment by esselfe** [comment]
It's already in PRE_BUILD.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
