### PR TITLE
avogadro:bump to 1.99.0

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.11.2", minimum required is "3") 
Avogadro Generators not found at /usr/src/avogadrolibs-1.97.0/../avogadrogenerators!
-- Could NOT find LIBARCHIVE (missing: LIBARCHIVE_INCLUDE_DIR LIBARCHIVE_LIBRARY) 
msym include dir /usr/lib64/cmake/libmsym/../../../include
-- Configuring done (1.7s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBARCHIVE_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /usr/src/avogadrolibs-1.97.0/avogadro/qtplugins/plugindownloader
   used as include directory in directory /usr/src/avogadrolibs-1.97.0/avogadro/qtplugins/plugindownloader
   used as include directory in directory /usr/src/avogadrolibs-1.97.0/avogadro/qtplugins/plugindownloader
   used as include directory in directory /usr/src/avogadrolibs-1.97.0/avogadro/qtplugins/plugindownloader
   used as include directory in directory /usr/src/avogadrolibs-1.97.0/avogadro/qtplugins/plugindownloader
   used as include directory in directory /usr/src/avogadrolibs-1.97.0/avogadro/qtplugins/plugindownloader
   used as include directory in directory /usr/src/avogadrolibs-1.97.0/avogadro/qtplugins/plugindownloader
LIBARCHIVE_LIBRARY (ADVANCED)
    linked by target "PluginDownloader" in directory /usr/src/avogadrolibs-1.97.0/avogadro/qtplugins/plugindownloader

CMake Error in avogadro/qtplugins/plugindownloader/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "PluginDownloader":

    "LIBARCHIVE_INCLUDE_DIR-NOTFOUND"



CMake Error in avogadro/qtplugins/plugindownloader/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "PluginDownloader":

    "LIBARCHIVE_INCLUDE_DIR-NOTFOUND"



-- Generating done (0.7s)
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
    SYSCONF_INSTALL_DIR


CMake Generate step failed.  Build files cannot be regenerated correctly.
ERROR: BUILD does not call prepare_install or installs zero files!

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
