### PR TITLE
ncdu:bump to 2.3

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
2023-08-16 18:12:51 (2.08 MB/s) - '/tmp/ncdu-2.3.tar.gz' saved [56608/56608]

Building ncdu version 2.3
zig build -Doptimize=ReleaseFast
make: zig: No such file or directory
make: *** [Makefile:20: release] Error 127
Creating /var/log/lunar/compile/ncdu-2.3.bz2 
! Problem detected during BUILD

**Comment by esselfe** [comment]
Even after adding zig to DEPENDS it fails with:

[...]
zig build -Doptimize=ReleaseFast
/usr/src/ncdu-2.3/build.zig:6:21: error: root struct of file 'std' has no member named 'Build'
pub fn build(b: *std.Build) void {
                 ~~~^~~~~~
referenced by:
    runBuild: /usr/lib/zig/build_runner.zig:231:45
    usage__anon_5084: /usr/lib/zig/build_runner.zig:242:13
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

make: *** [Makefile:20: release] Error 1

**Comment by esselfe** [comment]
Even after adding zig to DEPENDS it fails with:

[...]
+ running "default_make"
zig build -Doptimize=ReleaseFast
/usr/src/ncdu-2.3/build.zig:6:21: error: root struct of file 'std' has no member named 'Build'
pub fn build(b: *std.Build) void {
                 ~~~^~~~~~
referenced by:
    runBuild: /usr/lib/zig/build_runner.zig:231:45
    usage__anon_5084: /usr/lib/zig/build_runner.zig:242:13
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

make: *** [Makefile:20: release] Error 1

**Comment by stumbles** [comment]
This cannot be bumped. It requires zig 0.11 or greater. Currnet zig cannot be bumped because it requires llvm/lld 16.x or greater.

**Pull request closed without merging**
