### PR TITLE
influxdb:bump to 2.4.0

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by stumbles** [comment]
You need to fix the go module.

**Comment by lhw828** [comment]
Retest this please.

**Comment by esselfe** [comment]
There's just the last && in PRE_BUILD to remove and the build starts but fails to install.
Here's the last messages:
[...]
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/jmespath/go-jmespath v0.4.0
go: downloading github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.0.0
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
# /usr/bin/pkgconf --cflags  -- flux
Package flux was not found in the pkg-config search path.
Perhaps you should add the directory containing `flux.pc'
to the PKG_CONFIG_PATH environment variable
Package 'flux', required by 'virtual:world', not found
/usr/bin/pkgconf: exit status 1
install: cannot stat '/usr/src/influxdb-2.4.0/bin/influxd': No such file or directory

Creating /var/log/lunar/compile/influxdb-2.4.0.xz 
! Problem detected during BUILD

**Comment by lhw828** [comment]
go: warning: github.com/Azure/go-autorest/autorest/adal@v0.9.13: retracted by module author: retracted due to token refresh errors
go: warning: github.com/klauspost/compress@v1.14.2: retracted by module author
go: to switch to the latest unretracted version, run:
	go get <module>@latest
# pkg-config --cflags  -- flux
Package flux was not found in the pkg-config search path.
Perhaps you should add the directory containing `flux.pc'
to the PKG_CONFIG_PATH environment variable
Package 'flux', required by 'virtual:world', not found
pkg-config: exit status 1
install: cannot stat '/usr/src/influxdb-2.7.1/bin/influxd': No such file or directory
Creating /var/log/lunar/compile/influxdb-2.7.1.bz2

**Comment by stumbles** [comment]
This is replaced with https://github.com/lunar-linux/moonbase-other/pull/2822

**Pull request closed without merging**
