### PR TITLE
swayshot:bump to 2.7.3

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by esselfe** [comment]
Cannot test, dependency won't build (wlroots).

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by lhw828** [comment]
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES 
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Dependency wayland-server found: NO found 1.20.0 but need: '>=1.21'
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency wayland-server found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency wayland-server

meson.build:103:0: ERROR: Neither a subproject directory nor a wayland.wrap file was found.

A full log can be found at /usr/src/wlroots-0.16.2/build/meson-logs/meson-log.txt
Creating /var/log/lunar/compile/wlroots-0.16.2.bz2

**Comment by esselfe** [comment]
Closing with https://github.com/lunar-linux/moonbase-other/pull/2889

**Pull request closed without merging**
