### PR TITLE
a2ps:bump to 4.15.5

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by lhw828** [comment]
[71/79] Linking target plugins/threaded/src/liblcms2_threaded.so
FAILED: plugins/threaded/src/liblcms2_threaded.so 
gcc  -o plugins/threaded/src/liblcms2_threaded.so plugins/threaded/src/liblcms2_threaded.so.p/threaded_core.c.o plugins/threaded/src/liblcms2_threaded.so.p/threaded_main.c.o plugins/threaded/src/liblcms2_threaded.so.p/threaded_scheduler.c.o plugins/threaded/src/liblcms2_threaded.so.p/threaded_split.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,liblcms2_threaded.so -s -Wl,-z,relro,-z,now -O2 -march=x86-64 -fno-plt -fexceptions -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-clash-protection '-Wl,-rpath,$ORIGIN/../../../src' -Wl,-rpath-link,/usr/src/lcms2-2.15/build/src src/liblcms2.so.2.0.15 -Wl,--end-group
/usr/bin/ld: plugins/threaded/src/liblcms2_threaded.so.p/threaded_core.c.o: in function `_cmsThrCreateWorker':
threaded_core.c:(.text+0x6d): undefined reference to `pthread_create'
/usr/bin/ld: plugins/threaded/src/liblcms2_threaded.so.p/threaded_core.c.o: in function `_cmsThrJoinWorker':
threaded_core.c:(.text+0xbb): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
[72/79] Compiling C object plugins/threaded/testbed/threaded_testbed.p/threaded_testbed.c.o
../plugins/threaded/testbed/threaded_testbed.c:508:18: warning: 'SpeedTest8bitsRGBA' defined but not used [-Wunused-function]
  508 | cmsFloat64Number SpeedTest8bitsRGBA(cmsContext ct, cmsHPROFILE hlcmsProfileIn, cmsHPROFILE hlcmsProfileOut)
      |                  ^~~~~~~~~~~~~~~~~~
../plugins/threaded/testbed/threaded_testbed.c:458:6: warning: 'Comparative' defined but not used [-Wunused-function]
  458 | void Comparative(const char* Title, perf_fn fn1, perf_fn fn2, const char* inICC, const char* outICC)
      |      ^~~~~~~~~~~
[73/79] Generating symbol file plugins/fast_float/src/liblcms2_fast_float.so.p/liblcms2_fast_float.so.symbols
[74/79] Compiling C object testbed/testcms.p/testcms2.c.o
../testbed/testcms2.c: In function 'main':
../testbed/testcms2.c:9226:20: warning: unused variable 'DoZooTests' [-Wunused-variable]
 9226 |     cmsInt32Number DoZooTests = 0;
      |                    ^~~~~~~~~~
In file included from ../testbed/testcms2.c:27:
../testbed/testcms2.h:43:28: warning: ignoring return value of 'chdir' declared with attribute 'warn_unused_result' [-Wunused-result]
   43 | #    define CHDIR(a) (void)chdir(a)
      |                            ^~~~~~~~
../testbed/testcms2.c:9246:13: note: in expansion of macro 'CHDIR'
 9246 |             CHDIR(argv[2]);
      |             ^~~~~
At top level:
../testbed/testcms2.c:5181:16: warning: 'CheckDictionary16' defined but not used [-Wunused-function]
 5181 | cmsInt32Number CheckDictionary16(cmsInt32Number Pass,  cmsHPROFILE hProfile)
      |                ^~~~~~~~~~~~~~~~~
[75/79] Compiling C object plugins/fast_float/testbed/fast_float_testbed.p/fast_float_testbed.c.o
../plugins/fast_float/testbed/fast_float_testbed.c: In function 'CheckSingleFormatter15':
../plugins/fast_float/testbed/fast_float_testbed.c:122:40: warning: variable 'bytes' set but not used [-Wunused-but-set-variable]
  122 |        cmsInt32Number i, j, nChannels, bytes;
      |                                        ^~~~~
At top level:
../plugins/fast_float/testbed/fast_float_testbed.c:1595:18: warning: 'SpeedTest15bitsRGBA' defined but not used [-Wunused-function]
 1595 | cmsFloat64Number SpeedTest15bitsRGBA(cmsContext ct, cmsHPROFILE hlcmsProfileIn, cmsHPROFILE hlcmsProfileOut)
      |                  ^~~~~~~~~~~~~~~~~~~
../plugins/fast_float/testbed/fast_float_testbed.c:1504:18: warning: 'SpeedTest8bitsRGBA' defined but not used [-Wunused-function]
 1504 | cmsFloat64Number SpeedTest8bitsRGBA(cmsContext ct, cmsHPROFILE hlcmsProfileIn, cmsHPROFILE hlcmsProfileOut)
      |                  ^~~~~~~~~~~~~~~~~~
../plugins/fast_float/testbed/fast_float_testbed.c:1193:9: warning: 'ValidFloat2' defined but not used [-Wunused-function]
 1193 | cmsBool ValidFloat2(cmsFloat32Number a, cmsFloat32Number b)
      |         ^~~~~~~~~~~
../plugins/fast_float/testbed/fast_float_testbed.c:1074:6: warning: 'CheckLab2Roundtrip' defined but not used [-Wunused-function]
 1074 | void CheckLab2Roundtrip(void)
      |      ^~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
Creating /var/log/lunar/compile/lcms2-2.15.bz2

**Comment by esselfe** [comment]
Everything alright here.

**Pull request merged**
