### PR TITLE
freshplayerplugin:bump to 0.3.11

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
Creating /var/log/lunar/md5sum/nss-3.92
]0;033ca4b84de6 lin[215118]: compiling pepperflash Downloading source file pepperflash-32.0.0.465.tar.gz for module pepperflash
--2023-08-17 07:32:14--  https://fpdownload.adobe.com/pub/flashplayer/pdc/32.0.0.465/flash_player_ppapi_linux.x86_64.tar.gz
Resolving fpdownload.adobe.com... 2.16.224.137, 2a02:26f0:5c00:19f::11e2, 2a02:26f0:5c00:1a0::11e2, ...
Connecting to fpdownload.adobe.com|2.16.224.137|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.adobe.com/es/products/flashplayer/end-of-life-alternative.html [following]
--2023-08-17 07:32:14--  https://www.adobe.com/es/products/flashplayer/end-of-life-alternative.html
Resolving www.adobe.com... 185.43.182.8, 2a02:26f0:5c00::685a:cd82, 2a02:26f0:5c00::58dd:d590
Connecting to www.adobe.com|185.43.182.8|:443... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.

--2023-08-17 07:47:16--  (try: 2)  https://www.adobe.com/es/products/flashplayer/end-of-life-alternative.html
Connecting to www.adobe.com|185.43.182.8|:443... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.

--2023-08-17 08:02:18--  (try: 3)  https://www.adobe.com/es/products/flashplayer/end-of-life-alternative.html
Connecting to www.adobe.com|185.43.182.8|:443... connected.
HTTP request sent, awaiting response... Build timed out (after 150 minutes). Marking the build as failed.
FATAL: Caught exception while loading script 'Build Lunar Modules (docker)'
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
	at hudson.Proc$LocalProc.join(Proc.java:332)
	at hudson.Launcher$ProcStarter.join(Launcher.java:534)
	at org.jenkinsci.plugins.managedscripts.ScriptBuildStep.perform(ScriptBuildStep.java:162)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:816)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:164)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:524)
	at hudson.model.Run.execute(Run.java:1897)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Build step 'Execute managed script' marked build as failure
Discard old builds...
#3435 is removed because old than numToKeep

**Comment by esselfe** [comment]
Can't test because pepperflash is broken.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Closing with PR#3684.

**Pull request closed without merging**
