### PR TITLE
mythtv: Bump to 33.1. Adding two patches. A rework of DEPENSD and

### PR DESCRIPTION
**Pull request by stumbles**
a bit of BUILD.

### CODE REVIEW

**Comment by esselfe** [comment]
Can't test because libbluray fails with:

[javac] error: Source option 6 is no longer supported. Use 7 or later.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Like other PRs trying to pull in pulseaudio, the failure is with CI and meson finding no metadata package.

**Comment by esselfe** [comment]
So libbluray succeeded with the just-commited sun-jdk (https://github.com/lunar-linux/moonbase-other/pull/3298)... mythtv built nicely now.

**Pull request merged**
