### PR TITLE
wlroots: Bump to 0.18.0.

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by stumbles** [comment]
Fails on;
`Dependency libdrm found: NO found 2.4.120 but need: '>=2.4.122'`

even though libdrm is at 2.4.122.

CI is confused.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by esselfe** [comment]
This bump broke sway...

**Pull request merged**
