### PR TITLE
lttng-modules: version bumped to 2.13.14

### PR DESCRIPTION
**Pull request by esselfe**

### CODE REVIEW

**Comment by esselfe** [comment]
The CI failed with:

```
make[1]: *** /lib/modules/5.15.27-lts/build: No such file or directory.  Stop.
```

**Comment by stumbles** [comment]
Looks like a CI issue, or it needs kernel-headers depends.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Doesn't install depends kernel-headers

**Comment by stumbles** [comment]
Comparing this line from CI; `KCPPFLAGS='' \` is not the same when compiled locally and showing; `KCPPFLAGS='' " \`.

Is CI really dropping the second double quote or is it just a visual bug of the out?

**Comment by stumbles** [comment]
Closing with PR#4392.

**Pull request closed without merging**
