### PR TITLE
libplacebo:bump to 6.292.1

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
checking whether OpenCL headers 3.0 are available... checking how to run the C preprocessor... cpp
yes
checking for inline... inline
checking for size_t... yes
checking for an ANSI C-conforming const... yes
checking whether C compiler accepts -Wno-deprecated-declarations... yes
checking for GNU libc compatible malloc... yes
checking for GNU libc compatible realloc... yes
checking for strstr... yes
configure: using system OpenCL headers
configure: using the official default vendors directory (/etc/OpenCL/vendors)
configure: using the official default layers directory (/etc/OpenCL/layers)
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating tests/Makefile
config.status: creating OpenCL.pc
config.status: creating ocl-icd.pc
config.status: creating tests/atlocal
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing tests/atconfig commands
ruby icd_generator.rb --mode database --database ./ocl_interface.yaml \
	
make: ruby: No such file or directory
make: *** [Makefile:1670: stamp-generator] Error 127
Creating /var/log/lunar/compile/ocl-icd-2.3.2.bz2 
! Problem detected during BUILD

**Comment by stumbles** [comment]
Retest this please.

**Comment by esselfe** [comment]
Can't test because the ocl-icd dependency is failing.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Closing with commit f889507a4385652ca2e2b4cc65cd9631bee91348.

**Pull request closed without merging**
