### PR TITLE
libopenraw: Bump to 0.3.7.

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by stumbles** [comment]
Guess I was to quick on the draw. Looks like the rustc bump hasn't made its way into CI. This was the error prompting the rustc + config.toml change;

`error[E0635]: unknown feature `stdsimd`
  --> /usr/src/libopenraw-0.3.7/lib/mp4/vendor/ahash/src/lib.rs:33:42
   |
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error`

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Another instance CI won't pull in the most current depends (rustc), instead uses older version.

**Comment by stumbles** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
