### PR TITLE
foomatic-filters:depends a2ps

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
Retest this please.

**Comment by esselfe** [comment]
a2ps fails to build, so I can't really test.

**Comment by esselfe** [comment]
Tested once @stumbles corrected a2ps, but fails with those messages:
[...]
gcc -DHAVE_CONFIG_H -I.  -DCONFIG_PATH='"/etc/foomatic"'  -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include  -DHAVE_DBUS -O2 -march=x86-64 -pipe -MT foomatic_rip-colord.o -MD -MP -MF .deps/foomatic_rip-colord.Tpo -c -o foomatic_rip-colord.o `test -f 'colord.c' || echo './'`colord.c
mv -f .deps/foomatic_rip-colord.Tpo .deps/foomatic_rip-colord.Po
gcc -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include  -DHAVE_DBUS -O2 -march=x86-64 -pipe  -s -Wl,-z,now -o foomatic-rip foomatic_rip-foomaticrip.o foomatic_rip-options.o foomatic_rip-pdf.o foomatic_rip-postscript.o foomatic_rip-util.o foomatic_rip-spooler.o foomatic_rip-process.o foomatic_rip-renderer.o foomatic_rip-fileconverter.o foomatic_rip-colord.o -ldbus-1  -lm 
/usr/bin/ld: foomatic_rip-options.o:(.bss+0x280): multiple definition of 'postpipe'; foomatic_rip-foomaticrip.o:(.bss+0x448): first defined here
/usr/bin/ld: foomatic_rip-options.o:(.bss+0x2420): multiple definition of 'printer_model'; foomatic_rip-foomaticrip.o:(.bss+0x340): first defined here
/usr/bin/ld: foomatic_rip-options.o:(.bss+0x180): multiple definition of 'cupsfilter'; foomatic_rip-foomaticrip.o:(.bss+0x20): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:470: foomatic-rip] Error 1
make[1]: Leaving directory '/usr/src/foomatic-filters-4.0.17'
make: *** [Makefile:369: all] Error 2
Creating /var/log/lunar/compile/foomatic-filters-4.0.17.xz 
! Problem detected during BUILD

**Comment by stumbles** [comment]
@esselfe;

I get the same error. It appears from a mailing list archive as far back as 2014 this was taken over by the cups-filters maintainers, see https://lists.archive.carbon60.com/gentoo/user/288187#288187. The only real purpose of foomatic-filters is to provide /usr/bin/foomatic-rip and is now provided by cups-filters. 

So I think we send foomatic-filters to the great ether, and add REPLACES=foomatic-filters to the DETAILS of cup-filters. It would also allow removing/conflict of between the two modules.

**Comment by esselfe** [comment]
Closing with https://github.com/lunar-linux/moonbase-other/pull/3045

**Pull request closed without merging**
