### PR TITLE
libblockdev: version bumped to 3.1.0

### PR DESCRIPTION
**Pull request by esselfe**

### CODE REVIEW

**Comment by esselfe** [comment]
Fails at fetching libtasn1 with:

Connecting to ftp.rediris.es (ftp.rediris.es)|130.206.13.2|:443... connected.
OpenSSL: error:0A000152:SSL routines::unsafe legacy renegotiation disabled
Unable to establish SSL connection.

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by esselfe** [comment]
This time the CI failed at ndctl with:

../ndctl/dimm.c:1031:16: error: too many arguments to function 'ndctl_dimm_remove_key'

**Comment by stumbles** [comment]
FAILED: ndctl/ndctl.p/dimm.c.o 
gcc -Indctl/ndctl.p -Indctl -I../ndctl -I. -I.. -I/usr/include/uuid -I/usr/include/json-c -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O3 -Wchar-subscripts -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wshadow -Wsign-compare -Wstrict-prototypes -Wtype-limits -Wmaybe-uninitialized -Wdeclaration-after-statement -Wunused-result -D_FORTIFY_SOURCE=2 -include config.h -O2 -march=x86-64 -fno-plt -fexceptions -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-clash-protection -include version.h -MD -MQ ndctl/ndctl.p/dimm.c.o -MF ndctl/ndctl.p/dimm.c.o.d -o ndctl/ndctl.p/dimm.c.o -c ../ndctl/dimm.c
../ndctl/dimm.c: In function 'action_remove_passphrase':
../ndctl/dimm.c:1031:16: error: too many arguments to function 'ndctl_dimm_remove_key'
 1031 |         return ndctl_dimm_remove_key(dimm, param.master_pass ? ND_MASTER_KEY :
      |                ^~~~~~~~~~~~~~~~~~~~~
In file included from ../ndctl/dimm.c:25:
../ndctl/keys.h:51:19: note: declared here
   51 | static inline int ndctl_dimm_remove_key(struct ndctl_dimm *dimm)
      |                   ^~~~~~~~~~~~~~~~~~~~~

**Comment by stumbles** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
