### PR TITLE
rav1e:bump to 0.6.6

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by lhw828** [comment]
--   Package 'heimdal-gssapi', required by 'virtual:world', not found
-- Could NOT find GSSAPI (missing: GSSAPI_LIBRARIES GSSAPI_INCLUDE_DIR) 
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1l")  
-- http-parser version 2 was not found or disabled; using bundled 3rd-party sources.
-- Performing Test IS_WIMPLICIT_FALLTHROUGH_1_SUPPORTED
-- Performing Test IS_WIMPLICIT_FALLTHROUGH_1_SUPPORTED - Success
-- Found PCRE: /usr/lib/libpcre.so  
-- Looking for regcomp_l
-- Looking for regcomp_l - not found
-- Checking for module 'ssh2'
--   Package 'ssh2', required by 'virtual:world', not found
-- Could NOT find LibSSH2 (missing: LIBSSH2_LIBRARY LIBSSH2_INCLUDE_DIR) 
CMake Error at cmake/SelectSSH.cmake:13 (message):
  LIBSSH2 not found.  Set CMAKE_PREFIX_PATH if it is installed outside of the
  default search path.
Call Stack (most recent call first):
  src/CMakeLists.txt:45 (include)


-- Configuring incomplete, errors occurred!
See also "/usr/src/libgit2-1.7.0/libgit2-oosb/CMakeFiles/CMakeOutput.log".
See also "/usr/src/libgit2-1.7.0/libgit2-oosb/CMakeFiles/CMakeError.log".
Creating /var/log/lunar/compile/libgit2-1.7.0.bz2 
! Problem detected during BUILD

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
Retest this please.

**Comment by esselfe** [comment]
Closing with 82950edb21fa455acc67b7bbb815adfd0b0f0f0a

**Pull request closed without merging**
