### PR TITLE
midori: bump to 0.5.10 and adding a PRE_BUILD

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by v4hn** [comment]
retest this please

**Comment by stumbles** [comment]
retest this please

**Comment by stumbles** [comment]
retest this please

**Comment by stumbles** [comment]
Retest this please.

Last time then I do a bare metal reinstall.

**Comment by stumbles** [comment]
retest this please

**Comment by stumbles** [comment]
retest this please

**Pull request merged**
