### PR TITLE
VirtualBox: major version bump

### PR DESCRIPTION
**Pull request by v4hn**
works without problems for my setup

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by Ratler** [comment]
@v4hn could you verify whether your VirtualBox is linked against qt4 or qt5? I find quite a few references to qt4 in the source code but it only seem to build using qt5. With qt5 it works fine for me :+1:

**Comment by v4hn** [comment]
You're right. They depend on Qt5 now.
I updated the request.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
