### PR TITLE
docker-compose:bump to 1.29.2

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
go module is busted, fails on;

find: '/usr/lib/go': No such file or directory
Removed module: go-bootstrap
Building Go cmd/dist using /usr/lib/go1.19. (go1.19.5 linux/amd64)
cmd/dist
found packages main (build.go) and building_Go_requires_Go_1_20_6_or_later (notgo120.go) in /usr/src/go/src/cmd/dist

**Comment by stumbles** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
