### PR TITLE
whois: version bumped to 5.5.19

### PR DESCRIPTION
**Pull request by esselfe**

### CODE REVIEW

**Comment by esselfe** [comment]
Hmmm, it failed with:

utils.h:63:1: error: wrong number of arguments specified for 'malloc' attribute

but it built fine on my laptop. I'll try with 2 of my servers...

**Comment by esselfe** [comment]
No problems with them.

**Comment by stumbles** [comment]
Try adding just above the cat<<EOF line this; PSAFE=no

That disables threaded compiling, giving a clear view of the problem.

**Comment by stumbles** [comment]
Or trying adding this gentoo libidn detection patch;
https://gitweb.gentoo.org/repo/gentoo.git/plain/net-misc/whois/files/whois-5.3.0-libidn_automagic.patch

**Comment by stumbles** [comment]
I'll guess its glibc CI is using.

Compiles fine here.

**Pull request closed without merging**
