### PR TITLE
glm: new module

### PR DESCRIPTION
**Pull request by bsfc1685**

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by bsfc1685** [comment]
Note that the downloaded archive is named "0.9.8.1.tar.gz"...

**Comment by Florin65** [comment]
isn't cmake a needed depend?

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
