### PR TITLE
nettle: version bumped to 3.6

### PR DESCRIPTION
**Pull request by cody1632**

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by florin65** [comment]
Update it by hand. Thank you.

**Comment by cody1632** [comment]
what do you mean by hand?

**Comment by v4hn** [comment]
> what do you mean by hand?

independently of this pull-request: 10058b57fb7a5014425bfe0f185fdf75d6221cb2

**Pull request closed without merging**
