### PR TITLE
i3: bump to 4.13 again

### PR DESCRIPTION
**Pull request by rtlanceroad**
The old objects I am not sure whether it's caused by docker, I open it anyway.

### CODE REVIEW

**Comment by rtlanceroad** [comment]
@Florin65 Could you look at it?

**Comment by Ratler** [comment]
@rtlanceroad try and set PSAFE=no in the DETAILS file.

**Comment by rtlanceroad** [comment]
@Ratler Looks like setting PSAFE=no in DETAILS doesn't work.

**Comment by rtlanceroad** [comment]
What's caused the error btw? :)

**Comment by Ratler** [comment]
@rtlanceroad see line nr 5 in BUILD, it required to be built from an 'arch' specific directory - https://github.com/lunar-linux/moonbase-other/commit/bad2d3e5501acc033b5eb850435b8fc5fd0bc2f8#diff-92a920c5e26b561930729cdc2ff2cd4cR5

**Comment by rtlanceroad** [comment]
@Ratler I am kinda stupid, why does it need build from an 'arch' specific directory? I checked source directory quite for a while, nothing looks special. And are there any functions related to `$(arch)-pc-linux-gnu` ?

**Pull request merged**
