### PR TITLE
python-jsonschema:bump to 4.14.0

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by esselfe** [comment]
Fails with this error message:
`python3: can't open file '/usr/src/jsonschema-4.14.0/setup.py': [Errno 2] No such file or directory`

**Comment by esselfe** [comment]
Also 4.17.3 is out.

**Comment by stumbles** [comment]
It fails because the default_python_build function triggered by the TYPE=python3 (DETAILS) does not follow the "new method" of building/compiling many of these newer versions of python scripts. Create BUILD with the correct incantations and submit a PR.

**Comment by lhw828** [comment]
2023-07-20 06:45:15 (1.73 MB/s) - '/tmp/jsonschema-4.18.4.tar.gz' saved [325256]

Building python-jsonschema version 4.18.4
python3: can't open file '/usr/src/jsonschema-4.18.4/setup.py': [Errno 2] No such file or directory
cp: cannot stat '/usr/src/jsonschema-4.18.4/__pythondest3/*': No such file or directory
Creating /var/log/lunar/compile/python-jsonschema-4.18.4.bz2

**Comment by stumbles** [comment]
#2434 takes care of this problem. Closing

**Pull request closed without merging**
