### PR TITLE
Lhw828 master 464

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by stumbles** [comment]
Fails on pulseaudio.

**Comment by esselfe** [comment]
Here it fails with "Missing configure and/or Makefile!"

**Comment by esselfe** [comment]
Needs a "TYPE=cmake" in DETAILS, but then it fails with:

CMake Error at src/sdl-test-ui/CMakeLists.txt:19 (target_link_libraries):
  Target "projectM-Test-UI" links to:

    SDL2::SDL2main

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

**Comment by stumbles** [comment]
Closing with https://github.com/lunar-linux/moonbase-other/commit/c02fa7040f6354c15605f7800c5c1b3806f98364

**Pull request closed without merging**
