### PR TITLE
libplacebo: Bump to 6.338.0.

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by stumbles** [comment]
CI meson is tooooooo oooolllddd.

**Comment by esselfe** [comment]
Can't test because ocl-icd fails with `/usr/include/CL/cl_icd.h:21:10: fatal error: CL/cl_function_types.h: No such file or directory`

**Comment by stumbles** [comment]
Compiles fine here locally, as does version 5.264.0.

**Comment by esselfe** [comment]
Ok now that CUDA-OpenCL-headers has been updated everything builds fine.

**Pull request merged**
