### PR TITLE
dwl:bump to 0.3.1

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by esselfe** [comment]
Failed here because it wants Xwayland:
`xwayland/meson.build:28:3: ERROR: Problem encountered: Install "xwayland" or pass "-Dxwayland=disabled".
Required for Xwayland support.`

**Comment by lhw828** [comment]
Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES 
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Dependency wayland-server found: NO found 1.20.0 but need: '>=1.21'
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency wayland-server found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency wayland-server

meson.build:103:0: ERROR: Neither a subproject directory nor a wayland.wrap file was found.

A full log can be found at /usr/src/wlroots-0.16.2/build/meson-logs/meson-log.txt
Creating /var/log/lunar/compile/wlroots-0.16.2.bz2

**Comment by esselfe** [comment]
Fails with:

[...]
config.h:11:19: error: zero or negative size array 'rules'
   11 | static const Rule rules[] = {
      |                   ^~~~~
config.h:36:84: warning: excess elements in struct initializer
   36 |         { NULL,       0.55, 1,      1,    &layouts[0], WL_OUTPUT_TRANSFORM_NORMAL, 0, 0 },
      |                                                                                    ^
config.h:36:84: note: (near initialization for 'monrules[0]')
config.h:36:87: warning: excess elements in struct initializer
   36 |         { NULL,       0.55, 1,      1,    &layouts[0], WL_OUTPUT_TRANSFORM_NORMAL, 0, 0 },
      |                                                                                       ^
config.h:36:87: note: (near initialization for 'monrules[0]')
config.h:40:48: warning: ISO C forbids empty initializer braces [-Wpedantic]
   40 | static const struct xkb_rule_names xkb_rules = {
      |                                                ^
dwl.c: In function 'checkidleinhibitor':
dwl.c:632:44: error: 'bypass_surface_visibility' undeclared (first use in this function)
  632 |                 if (exclude != surface && (bypass_surface_visibility || (!tree
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~
dwl.c:632:44: note: each undeclared identifier is reported only once for each function it appears in
dwl.c: In function 'createmon':
dwl.c:946:71: error: 'fullscreen_bg' undeclared (first use in this function)
  946 |         m->fullscreen_bg = wlr_scene_rect_create(layers[LyrFS], 0, 0, fullscreen_bg);
      |                                                                       ^~~~~~~~~~~~~
dwl.c: In function 'createpointer':
dwl.c:1012:86: error: 'tap_and_drag' undeclared (first use in this function)
 1012 |                         libinput_device_config_tap_set_drag_enabled(libinput_device, tap_and_drag);
      |                                                                                      ^~~~~~~~~~~~
dwl.c:1013:91: error: 'drag_lock' undeclared (first use in this function)
 1013 |                         libinput_device_config_tap_set_drag_lock_enabled(libinput_device, drag_lock);
      |                                                                                           ^~~~~~~~~
dwl.c:1014:84: error: 'button_map' undeclared (first use in this function); did you mean 'buttons'?
 1014 |                         libinput_device_config_tap_set_button_map(libinput_device, button_map);
      |                                                                                    ^~~~~~~~~~
      |                                                                                    buttons
dwl.c:1021:81: error: 'disable_while_typing' undeclared (first use in this function)
 1021 |                         libinput_device_config_dwt_set_enabled(libinput_device, disable_while_typing);
      |                                                                                 ^~~~~~~~~~~~~~~~~~~~
dwl.c:1024:81: error: 'left_handed' undeclared (first use in this function)
 1024 |                         libinput_device_config_left_handed_set(libinput_device, left_handed);
      |                                                                                 ^~~~~~~~~~~
dwl.c:1027:94: error: 'middle_button_emulation' undeclared (first use in this function)
 1027 |                         libinput_device_config_middle_emulation_set_enabled(libinput_device, middle_button_emulation);
      |                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~
dwl.c:1030:84: error: 'scroll_method' undeclared (first use in this function)
 1030 |                         libinput_device_config_scroll_set_method (libinput_device, scroll_method);
      |                                                                                    ^~~~~~~~~~~~~
dwl.c:1033:83: error: 'click_method' undeclared (first use in this function)
 1033 |                         libinput_device_config_click_set_method (libinput_device, click_method);
      |                                                                                   ^~~~~~~~~~~~
dwl.c:1036:86: error: 'send_events_mode' undeclared (first use in this function)
 1036 |                         libinput_device_config_send_events_set_mode(libinput_device, send_events_mode);
      |                                                                                      ^~~~~~~~~~~~~~~~
dwl.c:1039:83: error: 'accel_profile' undeclared (first use in this function)
 1039 |                         libinput_device_config_accel_set_profile(libinput_device, accel_profile);
      |                                                                                   ^~~~~~~~~~~~~
dwl.c:1040:81: error: 'accel_speed' undeclared (first use in this function)
 1040 |                         libinput_device_config_accel_set_speed(libinput_device, accel_speed);
      |                                                                                 ^~~~~~~~~~~
dwl.c: In function 'mapnotify':
dwl.c:1531:1: warning: label 'unset_fullscreen' defined but not used [-Wunused-label]
 1531 | unset_fullscreen:
      | ^~~~~~~~~~~~~~~~
make: *** [Makefile:60: dwl.o] Error 1

**Comment by stumbles** [comment]
Closing with PR#3688.

**Pull request closed without merging**
